Repository LognLook/LognLook, pull requests merged in 2025-08, with the labels that each got.

#56 Feat[be]: Implement JWT-based user authentication and login system
  server/.env.sample
  server/.gitignore
  server/app/api/deps.py
  server/app/api/routers/log.py
  server/app/api/routers/pipeline.py
  server/app/api/routers/project.py
  server/app/api/routers/trouble.py
  server/app/api/routers/user.py
  server/app/api/routers/users.py
  server/app/core/config/settings.py
  server/app/core/utils/auth.py
  server/app/main.py
  server/app/models/user.py
  server/app/repositories/trouble.py
  server/app/repositories/user.py
  server/app/schemas/project.py
  server/app/schemas/trouble.py
  server/app/schemas/user.py
  server/app/services/log.py
  server/app/services/project.py
  server/app/services/trouble.py
  server/app/services/user.py
  server/poetry.lock
  server/pyproject.toml
Labels: feat

#59 feat[be]: Add Project Delete API and Update ROle Management Features
  server/app/api/routers/project.py
  server/app/core/enums/roles.py
  server/app/core/utils/roles_utils.py
  server/app/repositories/project.py
  server/app/schemas/project.py
  server/app/services/project.py
Labels: feat

#61 Refac[be]: Refactor trouble list endpoint and fix import error
  server/app/api/routers/log.py
  server/app/api/routers/pipeline.py
  server/app/api/routers/project.py
  server/app/api/routers/trouble.py
  server/app/main.py
  server/app/repositories/elasticsearch.py
  server/test/trouble/test_api_create_trouble.py
  server/test/trouble/test_api_delete_trouble.py
  server/test/trouble/test_api_update_trouble.py
Labels: feat

#65 Chore[fe]: Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
  docs/logstash/example.conf
Labels: documentation

#71 Refac: Add Apache 2.0 license and update database documentation
  LICENSE
  NOTICE
  README.md
  docs/database/README.md
  docs/database/mysql/lognlook.vuerd.json
  docs/database/mysql/notification.sql
  docs/database/mysql/project.sql
  docs/database/mysql/project_setting.sql
  docs/database/mysql/trouble.sql
  docs/database/mysql/trouble_log.sql
  docs/database/mysql/user.sql
  docs/database/mysql/user_project.sql
  docs/database/mysql/users.sql
  docs/database/opensearch/index-mapping.json
  docs/logstash/example.conf
  front/src/main.tsx
  server/app/core/config/opensearch_config.py
  server/app/main.py
  server/app/repositories/opensearch.py
  server/poetry.lock
  server/pyproject.toml
  server/test/core/config/test_opensearch_config.py
  server/test/integration/test_basic_functionality.py
Labels: refactor
